const COLLECTION = [
  {
    "id": 1,
    "ma_bt": "0001",
    "name": "Bình hoa văn Chữ vạn",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng ta",
    "size": "28*60 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0001.jpeg"
  },
  {
    "id": 2,
    "ma_bt": "0002",
    "name": "Người xoay",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đá nhân tạo - Nâu vàng",
    "size": "30*30 cm",
    "period": "1968",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0002.jpeg"
  },
  {
    "id": 3,
    "ma_bt": "0003",
    "name": "Vũ Nữ chăm pa",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đá nhân tạo - Xám",
    "size": "27*77 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0003.jpeg"
  },
  {
    "id": 4,
    "ma_bt": "0004",
    "name": "Bình một Cò tùng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng nâu, xanh dương",
    "size": "40*85 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0004.jpeg"
  },
  {
    "id": 5,
    "ma_bt": "0005",
    "name": "Vua Khơ-me",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đồng",
    "size": "30*23 cm",
    "period": "1950s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0005.jpeg"
  },
  {
    "id": 6,
    "ma_bt": "0006",
    "name": "Bình Trôn ốc",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - trắng ta",
    "size": "28*22 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0006.jpeg"
  },
  {
    "id": 7,
    "ma_bt": "0007",
    "name": "Bình Hai quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh cô ban",
    "size": "35*25 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0007.jpeg"
  },
  {
    "id": 8,
    "ma_bt": "0008",
    "name": "Đĩa bá hoa",
    "category": "Đĩa & Chén",
    "filterKey": "Đĩa",
    "material": "Gốm - Trắng ta",
    "size": "35 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0008.jpeg"
  },
  {
    "id": 9,
    "ma_bt": "0009",
    "name": "Bình Rồng lá",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng ta - Nâu",
    "size": "22*25 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0009.jpeg"
  },
  {
    "id": 10,
    "ma_bt": "0010",
    "name": "Tượng La hán",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đất nung phủ sơn màu nâu",
    "size": "22*30 cm",
    "period": "1980",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0010.jpeg"
  },
  {
    "id": 11,
    "ma_bt": "0011",
    "name": "Tuyết sơn",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Men xanh đồng",
    "size": "22*30 cm",
    "period": "1980",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0011.jpeg"
  },
  {
    "id": 12,
    "ma_bt": "0012",
    "name": "Bình hoa Nguyễn Hữu Cảnh",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - trắng ta",
    "size": "30*85 cm",
    "period": "1997",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0012.jpeg"
  },
  {
    "id": 13,
    "ma_bt": "0013",
    "name": "Bình hoa 300 năm Biên hòa, ĐN (Ng.H. Cảnh)",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - trắng ta",
    "size": "25*65 cm",
    "period": "1997",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0013.jpeg"
  },
  {
    "id": 14,
    "ma_bt": "0014",
    "name": "Bình hoa 300 năm Biên hòa, ĐN (Trịnh Hoài Đức)",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng ta",
    "size": "25*65 cm",
    "period": "1997",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0014.jpeg"
  },
  {
    "id": 15,
    "ma_bt": "0015",
    "name": "Bình hoa Bác Tôn",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "25*65 cm",
    "period": "1997",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0015.jpeg"
  },
  {
    "id": 16,
    "ma_bt": "0016",
    "name": "Bình hoa Bác Hồ + Bác Tôn",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "25*65 cm",
    "period": "1997",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0016.jpeg"
  },
  {
    "id": 17,
    "ma_bt": "0017",
    "name": "Khổng Tử",
    "category": "Đất nung",
    "filterKey": "Đất nung",
    "material": "Đất nung",
    "size": "35*65 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0017.jpeg"
  },
  {
    "id": 18,
    "ma_bt": "0018",
    "name": "Bình Trống Đồng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu đỏ",
    "size": "22*50 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0018.jpeg"
  },
  {
    "id": 19,
    "ma_bt": "0019",
    "name": "Bình hoa miệng loe",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng nâu",
    "size": "15*40 cm",
    "period": "1980",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0019.jpeg"
  },
  {
    "id": 20,
    "ma_bt": "0020",
    "name": "Bình hoa dây lá nhuyễn",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu đậm nhạt",
    "size": "20*35 cm",
    "period": "1990",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0020.jpeg"
  },
  {
    "id": 21,
    "ma_bt": "0021",
    "name": "Bình hoa khoảng hai quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh",
    "size": "20*40 cm",
    "period": "1988",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0021.jpeg"
  },
  {
    "id": 22,
    "ma_bt": "0022",
    "name": "Chóe tích cổ",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng ta",
    "size": "20*28 cm",
    "period": "1970",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0022.jpeg"
  },
  {
    "id": 23,
    "ma_bt": "0023",
    "name": "Hủ lộng dây lá trắng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng ta",
    "size": "27*30 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0023.jpeg"
  },
  {
    "id": 24,
    "ma_bt": "0024",
    "name": "Bình hoa nâu đỏ",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh",
    "size": "22*30 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0024.jpeg"
  },
  {
    "id": 25,
    "ma_bt": "0025",
    "name": "Bình cá",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Đỏ huyết dụ",
    "size": "13*18 cm",
    "period": "2006",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0025.jpeg"
  },
  {
    "id": 26,
    "ma_bt": "0026",
    "name": "Bình lộng trống đồng quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "22*70 cm",
    "period": "2000",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0026.jpeg"
  },
  {
    "id": 27,
    "ma_bt": "0027",
    "name": "Bình hoa men khử",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Đồng khử",
    "size": "12*22 cm",
    "period": "2006",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0027.jpeg"
  },
  {
    "id": 28,
    "ma_bt": "0028",
    "name": "Ống cắm bút",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu",
    "size": "10*16 cm",
    "period": "2006",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0028.jpeg"
  },
  {
    "id": 29,
    "ma_bt": "0029",
    "name": "Bình dây lá lộng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh ngọc",
    "size": "22*50 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0029.jpeg"
  },
  {
    "id": 30,
    "ma_bt": "0030",
    "name": "Bình hoa đường diềm",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Xanh ngọc",
    "size": "18*25 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0030.jpeg"
  },
  {
    "id": 31,
    "ma_bt": "0031",
    "name": "Bình hoa quai sách trống đồng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh nâu",
    "size": "25*50 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0031.jpeg"
  },
  {
    "id": 32,
    "ma_bt": "0032",
    "name": "Chân đèn",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Nâu vàng",
    "size": "30*60 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0032.jpeg"
  },
  {
    "id": 33,
    "ma_bt": "0033",
    "name": "Tượng đầu Khơme",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đá nhân tạo",
    "size": "17*24 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0033.jpeg"
  },
  {
    "id": 34,
    "ma_bt": "0034",
    "name": "Đào xách giỏ cá",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao  - Trắng",
    "size": "45*120 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0034.jpeg"
  },
  {
    "id": 35,
    "ma_bt": "0035",
    "name": "Bình dây lá",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu - Trắng ta",
    "size": "22*28 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0035.jpeg"
  },
  {
    "id": 36,
    "ma_bt": "0036",
    "name": "Bình dây lá",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu - Trắng ta",
    "size": "22*28 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0036.jpeg"
  },
  {
    "id": 37,
    "ma_bt": "0037",
    "name": "Bình dây lá",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu - Trắng ta",
    "size": "22*28 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0037.jpeg"
  },
  {
    "id": 38,
    "ma_bt": "0038",
    "name": "Bình quả đất",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "15*30 cm",
    "period": "1997",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0038.jpeg"
  },
  {
    "id": 39,
    "ma_bt": "0039",
    "name": "Bình hoa Tây nguyên",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Đen nâu",
    "size": "22*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0039.jpeg"
  },
  {
    "id": 40,
    "ma_bt": "0040",
    "name": "Thổi kèn",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Trắng ta",
    "size": "24*54 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0040.jpeg"
  },
  {
    "id": 41,
    "ma_bt": "0041",
    "name": "Bình quai sắt trống đồng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu",
    "size": "22*55 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0041.jpeg"
  },
  {
    "id": 42,
    "ma_bt": "0042",
    "name": "Cá",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - Nâu",
    "size": "30*45 cm",
    "period": "1990",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0042.jpeg"
  },
  {
    "id": 43,
    "ma_bt": "0043",
    "name": "Ốc",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm",
    "size": "30*45 cm",
    "period": "1990",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0043.jpeg"
  },
  {
    "id": 44,
    "ma_bt": "0044",
    "name": "Cầu Mỹ thuận",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Đất nung",
    "size": "45*45 cm",
    "period": "1997",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0044.jpeg"
  },
  {
    "id": 45,
    "ma_bt": "0045",
    "name": "Vũ điệu",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm – Nâu đỏ",
    "size": "15*60 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0045.jpeg"
  },
  {
    "id": 46,
    "ma_bt": "0046",
    "name": "Lư hương",
    "category": "Đồ thờ",
    "filterKey": "Đồ thờ",
    "material": "Gốm - Xanh nước biển",
    "size": "20*25 cm",
    "period": "1990",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0046.jpeg"
  },
  {
    "id": 47,
    "ma_bt": "0047",
    "name": "Lơ lửng",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu",
    "size": "30*35 cm",
    "period": "2000",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0047.jpeg"
  },
  {
    "id": 48,
    "ma_bt": "0048",
    "name": "Giỏ cá",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - Nâu",
    "size": "30*60 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0048.jpeg"
  },
  {
    "id": 49,
    "ma_bt": "0049",
    "name": "Bình đơm hoa kết trái",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh ngọc",
    "size": "30*60 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0049.jpeg"
  },
  {
    "id": 50,
    "ma_bt": "0050",
    "name": "Đèn lồng",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Xanh dương",
    "size": "30*35 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0050.jpeg"
  },
  {
    "id": 51,
    "ma_bt": "0051",
    "name": "Tượng thác nước ( tượng nhà mồ Tây Nguyên)",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - Nâu vàng",
    "size": "60*90 cm",
    "period": "2007",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0051.jpeg"
  },
  {
    "id": 52,
    "ma_bt": "0052",
    "name": "Đấu vật",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Xanh đồng",
    "size": "40*60 cm",
    "period": "1995",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0052.jpeg"
  },
  {
    "id": 53,
    "ma_bt": "0053",
    "name": "Bình xanh",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "25*60 cm",
    "period": "2000 F",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0053.jpeg"
  },
  {
    "id": 54,
    "ma_bt": "0054",
    "name": "Bình chia ô",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "15*40 cm",
    "period": "2015",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0054.jpeg"
  },
  {
    "id": 55,
    "ma_bt": "0055",
    "name": "Bình đồng tiền",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu",
    "size": "30*60 cm",
    "period": "2007",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0055.jpeg"
  },
  {
    "id": 56,
    "ma_bt": "0056",
    "name": "Phật nằm",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao - Trắng",
    "size": "110*35 cm",
    "period": "1970 F",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0056.jpeg"
  },
  {
    "id": 57,
    "ma_bt": "0057",
    "name": "Hũ lộng dây",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "30*30 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0057.jpeg"
  },
  {
    "id": 58,
    "ma_bt": "0058",
    "name": "Ống dù trang trí",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Xanh đồng",
    "size": "14*35 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0058.jpeg"
  },
  {
    "id": 59,
    "ma_bt": "0059",
    "name": "Bình dây lá lộng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh ngọc",
    "size": "22*50 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0059.jpeg"
  },
  {
    "id": 60,
    "ma_bt": "0060",
    "name": "Bình hoa",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "30*50 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0060.jpeg"
  },
  {
    "id": 61,
    "ma_bt": "0061",
    "name": "Vỏ đạn sau chiến tranh",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Xanh đồng",
    "size": "20*50 cm",
    "period": "1990 F",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0061.jpeg"
  },
  {
    "id": 62,
    "ma_bt": "0062",
    "name": "Bình hoa",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng xanh",
    "size": "30*65 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0062.jpeg"
  },
  {
    "id": 63,
    "ma_bt": "0063",
    "name": "Địa cầu",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Vàng",
    "size": "30*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0063.jpeg"
  },
  {
    "id": 64,
    "ma_bt": "0064",
    "name": "Chậu",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "12*40 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0064.jpeg"
  },
  {
    "id": 65,
    "ma_bt": "0065",
    "name": "Đèn lồng",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm – Xanh -Trắng",
    "size": "30*70 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0065.jpeg"
  },
  {
    "id": 66,
    "ma_bt": "0066",
    "name": "Bình hoa miệng xéo",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh",
    "size": "35*50 cm",
    "period": "1993",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0066.jpeg"
  },
  {
    "id": 67,
    "ma_bt": "0067",
    "name": "Lư Gốm",
    "category": "Đồ thờ",
    "filterKey": "Đồ thờ",
    "material": "Gốm - Vàng",
    "size": "20*25 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0067.jpeg"
  },
  {
    "id": 68,
    "ma_bt": "0068",
    "name": "Bình lọng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "20*40 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0068.jpeg"
  },
  {
    "id": 69,
    "ma_bt": "0069",
    "name": "Vòng xoáy",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu đen",
    "size": "25*70 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0069.jpeg"
  },
  {
    "id": 70,
    "ma_bt": "0070",
    "name": "Bình lục giác",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "40*70 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0070.jpeg"
  },
  {
    "id": 71,
    "ma_bt": "0071",
    "name": "Lồng đèn",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm – Vàng xanh",
    "size": "30*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0071.jpeg"
  },
  {
    "id": 72,
    "ma_bt": "0072",
    "name": "Giã gạo",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu",
    "size": "40*65 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0072.jpeg"
  },
  {
    "id": 73,
    "ma_bt": "0073",
    "name": "Bình hoa phù dung",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng đen",
    "size": "30*40 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0073.jpeg"
  },
  {
    "id": 74,
    "ma_bt": "0074",
    "name": "Bình đen vương",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Đen",
    "size": "25*50 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0074.jpeg"
  },
  {
    "id": 75,
    "ma_bt": "0075",
    "name": "Nét Tây nguyên",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu đỏ",
    "size": "25*60 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0075.jpeg"
  },
  {
    "id": 76,
    "ma_bt": "0076",
    "name": "Bình đất nung",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "18*25 cm",
    "period": "1995",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0076.jpeg"
  },
  {
    "id": 77,
    "ma_bt": "0077",
    "name": "Hồ lô",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "22*45 cm",
    "period": "2010",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0077.jpeg"
  },
  {
    "id": 78,
    "ma_bt": "0078",
    "name": "Lính canh xưa",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - Xanh",
    "size": "40*50 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0078.jpeg"
  },
  {
    "id": 79,
    "ma_bt": "0079",
    "name": "Mầm sống",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Xanh đồng",
    "size": "30*45 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0079.jpeg"
  },
  {
    "id": 80,
    "ma_bt": "0080",
    "name": "Chân đèn",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Đất nung - Phủ sơn",
    "size": "30*50 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0080.jpeg"
  },
  {
    "id": 81,
    "ma_bt": "0081",
    "name": "Hai mặt",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm",
    "size": "30*50 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0081.jpeg"
  },
  {
    "id": 82,
    "ma_bt": "0082",
    "name": "Thiếu nữ",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao",
    "size": "50*60 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0082.jpeg"
  },
  {
    "id": 83,
    "ma_bt": "0083",
    "name": "Bình Đồng sắt quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Men xanh đồng",
    "size": "30*60 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0083.jpeg"
  },
  {
    "id": 84,
    "ma_bt": "0084",
    "name": "Cầu mưa",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu",
    "size": "20*30 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0084.jpeg"
  },
  {
    "id": 85,
    "ma_bt": "0085",
    "name": "Mầm sống",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu",
    "size": "20*25 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0085.jpeg"
  },
  {
    "id": 86,
    "ma_bt": "0086",
    "name": "Vươn lên",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Xanh đen",
    "size": "45*65 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0086.jpeg"
  },
  {
    "id": 87,
    "ma_bt": "0087",
    "name": "Khúc tấu",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm",
    "size": "25*30 cm",
    "period": "1995",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0087.jpeg"
  },
  {
    "id": 88,
    "ma_bt": "0088",
    "name": "Miên múa",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm",
    "size": "25*65 cm",
    "period": "2005",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0088.jpeg"
  },
  {
    "id": 89,
    "ma_bt": "0089",
    "name": "Bình Mẫu tử",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "22*26 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0089.jpeg"
  },
  {
    "id": 90,
    "ma_bt": "0090",
    "name": "Bình Dây lá cổ",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "30*26 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0090.jpeg"
  },
  {
    "id": 91,
    "ma_bt": "0091",
    "name": "Tình thiêng liêng",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm – Xanh đồng",
    "size": "25*30 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0091.jpeg"
  },
  {
    "id": 92,
    "ma_bt": "0092",
    "name": "Bình Dây lá lộng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Xanh đồng",
    "size": "25*60 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0092.jpeg"
  },
  {
    "id": 93,
    "ma_bt": "0093",
    "name": "Bình  bưởi",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu đỏ xanh",
    "size": "40*65 cm",
    "period": "1998",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0093.jpeg"
  },
  {
    "id": 94,
    "ma_bt": "0094",
    "name": "Điệu múa chăm",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - nâu đỏ",
    "size": "22*60 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0094.jpeg"
  },
  {
    "id": 95,
    "ma_bt": "0095",
    "name": "Xoay Gốm chăm",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu đen",
    "size": "20*70 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0095.jpeg"
  },
  {
    "id": 96,
    "ma_bt": "0096",
    "name": "Bình cá",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh",
    "size": "22*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0096.jpeg"
  },
  {
    "id": 97,
    "ma_bt": "0097",
    "name": "Chuông gió",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Xanh",
    "size": "30*70 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0097.jpeg"
  },
  {
    "id": 98,
    "ma_bt": "0098",
    "name": "Chuông gió",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Xanh",
    "size": "30*70 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0098.jpeg"
  },
  {
    "id": 99,
    "ma_bt": "0099",
    "name": "Cồng chiêng",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu trắng",
    "size": "25*65 cm",
    "period": "2006",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0099.jpeg"
  },
  {
    "id": 100,
    "ma_bt": "0100",
    "name": "Đèn vườn",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Xanh đồng",
    "size": "40*65 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0100.jpeg"
  },
  {
    "id": 101,
    "ma_bt": "0101",
    "name": "Ươm mầm",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Vàng",
    "size": "40*50 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0101.jpeg"
  },
  {
    "id": 102,
    "ma_bt": "0102",
    "name": "Tượng phật",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - Đen",
    "size": "60*50 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0102.jpeg"
  },
  {
    "id": 103,
    "ma_bt": "0103",
    "name": "Xoay gốm",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Xanh nâu",
    "size": "40*50 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0103.jpeg"
  },
  {
    "id": 104,
    "ma_bt": "0104",
    "name": "Đinh hợi",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu vàng",
    "size": "40*60 cm",
    "period": "2006",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0104.jpeg"
  },
  {
    "id": 105,
    "ma_bt": "0105",
    "name": "Thổi tù và",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm – Nâu đỏ",
    "size": "40*60 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0105.jpeg"
  },
  {
    "id": 106,
    "ma_bt": "0106",
    "name": "Bình Trung thu",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "25*60 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0106.jpeg"
  },
  {
    "id": 107,
    "ma_bt": "0107",
    "name": "Bình Lưỡng Long tranh trâu",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu – Đen",
    "size": "30*50 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0107.jpeg"
  },
  {
    "id": 108,
    "ma_bt": "0108",
    "name": "Ốc biển",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm – Xanh cô ban",
    "size": "25*50 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0108.jpeg"
  },
  {
    "id": 109,
    "ma_bt": "0109",
    "name": "Tây Nguyên",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu",
    "size": "22*28 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0109.jpeg"
  },
  {
    "id": 110,
    "ma_bt": "0110",
    "name": "Sinh sôi",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu đỏ",
    "size": "25*65 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0110.jpeg"
  },
  {
    "id": 111,
    "ma_bt": "0111",
    "name": "Bình Hoa trống đồng hai quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Đen nâu",
    "size": "30*50 cm",
    "period": "1990",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0111.jpeg"
  },
  {
    "id": 112,
    "ma_bt": "0112",
    "name": "Chân đèn",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Trắng ta",
    "size": "30*60 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0112.jpeg"
  },
  {
    "id": 113,
    "ma_bt": "0113",
    "name": "Bình Lọc nước",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Xanh trắng",
    "size": "25*60 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0113.jpeg"
  },
  {
    "id": 114,
    "ma_bt": "0114",
    "name": "Lân",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm – Xanh đồng",
    "size": "100*80 cm",
    "period": "1940s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0114.jpeg"
  },
  {
    "id": 115,
    "ma_bt": "0115",
    "name": "Bình 1 dây lá xanh",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh",
    "size": "40*75 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0115.jpeg"
  },
  {
    "id": 116,
    "ma_bt": "0116",
    "name": "Bình 1 dây lá xanh",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh",
    "size": "40*75 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0116.jpeg"
  },
  {
    "id": 117,
    "ma_bt": "0117",
    "name": "Ếch",
    "category": "Điêu khắc",
    "filterKey": "Điêu khắc",
    "material": "Thạch cao",
    "size": "40*20 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0117.jpeg"
  },
  {
    "id": 118,
    "ma_bt": "0118",
    "name": "Cá heo",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - Xanh",
    "size": "40*60 cm",
    "period": "2008",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0118.jpeg"
  },
  {
    "id": 119,
    "ma_bt": "0119",
    "name": "Tuyết sơn",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Đất nung phủ sơn",
    "size": "35*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0119.jpeg"
  },
  {
    "id": 120,
    "ma_bt": "0120",
    "name": "Phật Ấn độ",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao",
    "size": "30*50 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0120.jpeg"
  },
  {
    "id": 121,
    "ma_bt": "0121",
    "name": "La hán",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đất nung",
    "size": "40*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0121.jpeg"
  },
  {
    "id": 122,
    "ma_bt": "0122",
    "name": "Tuyết sơn",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Đất nung",
    "size": "35*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0122.jpeg"
  },
  {
    "id": 123,
    "ma_bt": "0123",
    "name": "Phật nghìn tay nghìn mắt",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đất nung phủ sơn",
    "size": "25*45 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0123.jpeg"
  },
  {
    "id": 124,
    "ma_bt": "0124",
    "name": "Khơme",
    "category": "Điêu khắc",
    "filterKey": "Điêu khắc",
    "material": "Đá nhân tạo",
    "size": "18*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0124.jpeg"
  },
  {
    "id": 125,
    "ma_bt": "0125",
    "name": "Quan âm",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao",
    "size": "40*80 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0125.jpeg"
  },
  {
    "id": 126,
    "ma_bt": "0126",
    "name": "Ngạo nghễ",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu",
    "size": "61*55 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0126.jpeg"
  },
  {
    "id": 127,
    "ma_bt": "127",
    "name": "Ngạo nghễ",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu",
    "size": "61*55cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/127.jpeg"
  },
  {
    "id": 128,
    "ma_bt": "0128",
    "name": "Phật quan âm thủ quyển",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Xi măng",
    "size": "50*70 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0128.jpeg"
  },
  {
    "id": 129,
    "ma_bt": "0129",
    "name": "Mẫu tử",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu đỏ",
    "size": "75*70 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0129.jpeg"
  },
  {
    "id": 130,
    "ma_bt": "0130",
    "name": "Phố cổ",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm – Xanh đồng",
    "size": "40*70 cm",
    "period": "2007",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0130.jpeg"
  },
  {
    "id": 131,
    "ma_bt": "0131",
    "name": "Lồng đèn",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Xanh đồng",
    "size": "50*70 cm",
    "period": "2006",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0131.jpeg"
  },
  {
    "id": 132,
    "ma_bt": "0132",
    "name": "Đào xách giỏ cá",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao",
    "size": "50*130 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0132.jpeg"
  },
  {
    "id": 133,
    "ma_bt": "0133",
    "name": "Bình Cò tùng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh",
    "size": "22*50 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0133.jpeg"
  },
  {
    "id": 134,
    "ma_bt": "0134",
    "name": "Bồ câu",
    "category": "Điêu khắc",
    "filterKey": "Điêu khắc",
    "material": "Đá nhân tạo",
    "size": "25*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0134.jpeg"
  },
  {
    "id": 135,
    "ma_bt": "0135",
    "name": "Thiếu nữ cầm đào",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm – Xanh đồng",
    "size": "15*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0135.jpeg"
  },
  {
    "id": 136,
    "ma_bt": "0136",
    "name": "Chim bồ câu",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm – Trắng",
    "size": "35*30 cm",
    "period": "1960s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0136.jpeg"
  },
  {
    "id": 137,
    "ma_bt": "0137",
    "name": "Chim bồ câu",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm -Trắng",
    "size": "30*40 cm",
    "period": "1960s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0137.jpeg"
  },
  {
    "id": 138,
    "ma_bt": "0138",
    "name": "Bình Thiếu phụ nam xương",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Xanh nâu",
    "size": "20*30 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0138.jpeg"
  },
  {
    "id": 139,
    "ma_bt": "0139",
    "name": "Đầu phật",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao – Sơn đen",
    "size": "20*25 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0139.jpeg"
  },
  {
    "id": 140,
    "ma_bt": "0140",
    "name": "Mạnh mẫu - Mạnh tử",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm – Xanh đồng",
    "size": "30*40 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0140.jpeg"
  },
  {
    "id": 141,
    "ma_bt": "0141",
    "name": "Mạnh mẫu - Mạnh tử",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao",
    "size": "20*25 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0141.jpeg"
  },
  {
    "id": 142,
    "ma_bt": "0142",
    "name": "Thái thượng Lão quân",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm – Xanh trắng",
    "size": "15*60 cm",
    "period": "1960s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0142.jpeg"
  },
  {
    "id": 143,
    "ma_bt": "0143",
    "name": "Chim thần",
    "category": "Điêu khắc",
    "filterKey": "Điêu khắc",
    "material": "Thạch cao",
    "size": "25*35 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0143.jpeg"
  },
  {
    "id": 144,
    "ma_bt": "0144",
    "name": "Tượng Tara",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm – Xanh đồng",
    "size": "40*65 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0144.jpeg"
  },
  {
    "id": 145,
    "ma_bt": "0145",
    "name": "Thố cơm cua",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "35*20 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0145.jpeg"
  },
  {
    "id": 146,
    "ma_bt": "0146",
    "name": "Dĩa lá sen",
    "category": "Đĩa & Chén",
    "filterKey": "Đĩa",
    "material": "Gốm - Xanh đồng",
    "size": "25*25 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0146.jpeg"
  },
  {
    "id": 147,
    "ma_bt": "0147",
    "name": "Chân dung Thiếu nữ",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao",
    "size": "15*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0147.jpeg"
  },
  {
    "id": 148,
    "ma_bt": "0148",
    "name": "Cá tượng",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm – Xanh đồng",
    "size": "40*30 cm",
    "period": "1960s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0148.jpeg"
  },
  {
    "id": 149,
    "ma_bt": "0149",
    "name": "Quan âm",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao",
    "size": "14*50 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0149.jpeg"
  },
  {
    "id": 150,
    "ma_bt": "0150",
    "name": "Hũ Gà",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh",
    "size": "20*25 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0150.jpeg"
  },
  {
    "id": 151,
    "ma_bt": "0151",
    "name": "Thọ nhỏ",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm",
    "size": "10*25 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0151.jpeg"
  },
  {
    "id": 152,
    "ma_bt": "0152",
    "name": "Lưu Bình - Dương Lễ",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Sơn",
    "size": "20*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0152.jpeg"
  },
  {
    "id": 153,
    "ma_bt": "0153",
    "name": "Đào sách giỏ cá",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm – Xanh đồng",
    "size": "20*50 cm",
    "period": "1960s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0153.jpeg"
  },
  {
    "id": 154,
    "ma_bt": "0154",
    "name": "Tượng Nữ thần Hương quế",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đá nhân tạo",
    "size": "18*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0154.jpeg"
  },
  {
    "id": 155,
    "ma_bt": "0155",
    "name": "Bình Hông bầu",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "22*45 cm",
    "period": "1960s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0155.jpeg"
  },
  {
    "id": 156,
    "ma_bt": "0156",
    "name": "Phật nghìn tay nghìn mắt",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm – Xanh đồng",
    "size": "20*40 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0156.jpeg"
  },
  {
    "id": 157,
    "ma_bt": "0157",
    "name": "Tuyết sơn",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Đất nung phủ sơn",
    "size": "30*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0157.jpeg"
  },
  {
    "id": 158,
    "ma_bt": "0158",
    "name": "Bình Trà dẹp",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "25*20 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0158.jpeg"
  },
  {
    "id": 159,
    "ma_bt": "0159",
    "name": "Tướng quân",
    "category": "Điêu khắc",
    "filterKey": "Điêu khắc",
    "material": "Thạch cao",
    "size": "30*55 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0159.jpeg"
  },
  {
    "id": 160,
    "ma_bt": "0160",
    "name": "Thời gian",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Xanh đồng",
    "size": "20*50 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0160.jpeg"
  },
  {
    "id": 161,
    "ma_bt": "0161",
    "name": "Đào suy tư",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Thạch cao",
    "size": "25*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0161.jpeg"
  },
  {
    "id": 162,
    "ma_bt": "0162",
    "name": "Đào sách giỏ dâu",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - Xanh cô ban",
    "size": "20*70 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0162.jpeg"
  },
  {
    "id": 163,
    "ma_bt": "0163",
    "name": "Bình hoa phù dung",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng đen",
    "size": "35*40 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0163.jpeg"
  },
  {
    "id": 164,
    "ma_bt": "0164",
    "name": "Thiếu nữ và Mùa xuân",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm",
    "size": "20*50 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0164.jpeg"
  },
  {
    "id": 165,
    "ma_bt": "0165",
    "name": "Dĩa Lá sen",
    "category": "Đĩa & Chén",
    "filterKey": "Đĩa",
    "material": "Gốm – Xanh đồng",
    "size": "25*25 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0165.jpeg"
  },
  {
    "id": 166,
    "ma_bt": "0166",
    "name": "Bình sữa",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "20*24 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0166.jpeg"
  },
  {
    "id": 167,
    "ma_bt": "0167",
    "name": "Bình Lộng sen",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Xanh nâu",
    "size": "18*40 cm",
    "period": "1990",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0167.jpeg"
  },
  {
    "id": 168,
    "ma_bt": "0168",
    "name": "Bình Trà dẹp",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Xanh đồng",
    "size": "25*20 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0168.jpeg"
  },
  {
    "id": 169,
    "ma_bt": "0169",
    "name": "Bình hoa Chữ thọ",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "20*28 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0169.jpeg"
  },
  {
    "id": 170,
    "ma_bt": "0170",
    "name": "Bình hoa dây lá đen",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Đen",
    "size": "22*20 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0170.jpeg"
  },
  {
    "id": 171,
    "ma_bt": "0171",
    "name": "Niết bàn",
    "category": "Điêu khắc",
    "filterKey": "Điêu khắc",
    "material": "Thạch cao",
    "size": "15*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0171.jpeg"
  },
  {
    "id": 172,
    "ma_bt": "0172",
    "name": "Bồ nông",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - Nâu",
    "size": "40*50 cm",
    "period": "2008",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0172.jpeg"
  },
  {
    "id": 173,
    "ma_bt": "0173",
    "name": "Bình hoa đấu vật",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng nâu",
    "size": "25*60 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0173.jpeg"
  },
  {
    "id": 174,
    "ma_bt": "0174",
    "name": "Bình Cổ 4 quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "22*48 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0174.jpeg"
  },
  {
    "id": 175,
    "ma_bt": "0175",
    "name": "Bình hoa ly 2 quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh nâu",
    "size": "22*50 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0175.jpeg"
  },
  {
    "id": 176,
    "ma_bt": "0176",
    "name": "Bình Miệng loe",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "20*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0176.jpeg"
  },
  {
    "id": 177,
    "ma_bt": "0177",
    "name": "Bình hoa hai bợm",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Trắng ta",
    "size": "25*30 cm",
    "period": "1950s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0177.jpeg"
  },
  {
    "id": 178,
    "ma_bt": "0178",
    "name": "Bình Tứ giác hai bợm",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "15*22 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0178.jpeg"
  },
  {
    "id": 179,
    "ma_bt": "0179",
    "name": "La đa",
    "category": "Đất nung",
    "filterKey": "Đất nung",
    "material": "Đất nung phủ sơn",
    "size": "30*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0179.jpeg"
  },
  {
    "id": 180,
    "ma_bt": "0180",
    "name": "Hoa Bằng lăng",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Nâu cam",
    "size": "20*30 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0180.jpeg"
  },
  {
    "id": 181,
    "ma_bt": "0181",
    "name": "Tượng Nữ thần Hương quế",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đá nhân tạo",
    "size": "18*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0181.jpeg"
  },
  {
    "id": 182,
    "ma_bt": "0182",
    "name": "Cú mèo",
    "category": "Điêu khắc",
    "filterKey": "Điêu khắc",
    "material": "Đá nhân tạo",
    "size": "12*25 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0182.jpeg"
  },
  {
    "id": 183,
    "ma_bt": "0183",
    "name": "Hoa văn dây lá cổ",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Đen nâu",
    "size": "18*25 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0183.jpeg"
  },
  {
    "id": 184,
    "ma_bt": "0184",
    "name": "Bình Con công",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh cô ban",
    "size": "20*45 cm",
    "period": "",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0184.jpeg"
  },
  {
    "id": 185,
    "ma_bt": "0185",
    "name": "Phật suy tư",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đá nhân tạo",
    "size": "20*35 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0185.jpeg"
  },
  {
    "id": 186,
    "ma_bt": "0186",
    "name": "Tượng mẹ và chúa",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đá nhân tạo",
    "size": "50*155 cm",
    "period": "1936",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0186.jpeg"
  },
  {
    "id": 187,
    "ma_bt": "0187",
    "name": "Lu Bảo đại",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm – Xanh đồng",
    "size": "60*80 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0187.jpeg"
  },
  {
    "id": 188,
    "ma_bt": "0188",
    "name": "Đèn Trấn biên (Văn bia)",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Nâu vàng",
    "size": "30*45 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0188.jpeg"
  },
  {
    "id": 189,
    "ma_bt": "0189",
    "name": "Bình Quai vòi",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Xanh đồng",
    "size": "20*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0189.jpeg"
  },
  {
    "id": 190,
    "ma_bt": "0190",
    "name": "Bình Cổ trắng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Trắng ta",
    "size": "20*30 cm",
    "period": "1950s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0190.jpeg"
  },
  {
    "id": 191,
    "ma_bt": "0191",
    "name": "Bình Hoa mai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Trắng đen",
    "size": "18*20 cm",
    "period": "1980",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0191.jpeg"
  },
  {
    "id": 192,
    "ma_bt": "0192",
    "name": "La đa",
    "category": "Đất nung",
    "filterKey": "Đất nung",
    "material": "Đất nung phủ sơn",
    "size": "30*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0192.jpeg"
  },
  {
    "id": 193,
    "ma_bt": "0193",
    "name": "Tam thể",
    "category": "Đất nung",
    "filterKey": "Đất nung",
    "material": "Đất nung phủ sơn",
    "size": "35*65 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0193.jpeg"
  },
  {
    "id": 194,
    "ma_bt": "0194",
    "name": "Tôm",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm",
    "size": "40*10 cm",
    "period": "15/5/197",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0194.jpeg"
  },
  {
    "id": 195,
    "ma_bt": "0195",
    "name": "Mẫu tử",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Đá nhân tạo",
    "size": "20*30 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0195.jpeg"
  },
  {
    "id": 196,
    "ma_bt": "0196",
    "name": "Bình Hoa hai bợm",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Trắng đen",
    "size": "20*30 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0196.jpeg"
  },
  {
    "id": 197,
    "ma_bt": "0197",
    "name": "Bình Hoa trôn ốc",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "20*30 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0197.jpeg"
  },
  {
    "id": 198,
    "ma_bt": "0198",
    "name": "Bình Hoa bằng lăng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu đỏ",
    "size": "20*30 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0198.jpeg"
  },
  {
    "id": 199,
    "ma_bt": "0199",
    "name": "Bình 4 quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Trắng ta",
    "size": "25*45 cm",
    "period": "1960s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0199.jpeg"
  },
  {
    "id": 200,
    "ma_bt": "0200",
    "name": "Bình Công lộng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng",
    "size": "15*50 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0200.jpeg"
  },
  {
    "id": 201,
    "ma_bt": "0201",
    "name": "Bình Bắn cung",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh trắng",
    "size": "30*60 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0201.jpeg"
  },
  {
    "id": 202,
    "ma_bt": "0202",
    "name": "Vũ Nữ chăm",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đá nhân tạo",
    "size": "30*50 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0202.jpeg"
  },
  {
    "id": 203,
    "ma_bt": "0203",
    "name": "Phật Khơ-me",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Thạch cao",
    "size": "50*60 cm",
    "period": "",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0203.jpeg"
  },
  {
    "id": 204,
    "ma_bt": "0204",
    "name": "Lân đứng",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm",
    "size": "60*90 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0204.jpeg"
  },
  {
    "id": 205,
    "ma_bt": "0205",
    "name": "Sư tử",
    "category": "Điêu khắc",
    "filterKey": "Điêu khắc",
    "material": "Thạch cao",
    "size": "100*105 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0205.jpeg"
  },
  {
    "id": 206,
    "ma_bt": "0206",
    "name": "Bình Sen",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng xanh",
    "size": "40*100 cm",
    "period": "1998",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0206.jpeg"
  },
  {
    "id": 207,
    "ma_bt": "0207",
    "name": "Chân đèn 1980s",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Đất nung phủ sơn",
    "size": "40*50 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0207.jpeg"
  },
  {
    "id": 208,
    "ma_bt": "0208",
    "name": "Lính canh",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - Nâu vàng",
    "size": "30*50 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0208.jpeg"
  },
  {
    "id": 209,
    "ma_bt": "0209",
    "name": "Nhựa sống",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu đỏ",
    "size": "40*60 cm",
    "period": "1998",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0209.jpeg"
  },
  {
    "id": 210,
    "ma_bt": "0210",
    "name": "Chân đèn",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Xanh",
    "size": "20*40 cm",
    "period": "2007",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0210.jpeg"
  },
  {
    "id": 211,
    "ma_bt": "0211",
    "name": "Bất khuất",
    "category": "Điêu khắc",
    "filterKey": "Điêu khắc",
    "material": "Thạch cao",
    "size": "30*70 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0211.jpeg"
  },
  {
    "id": 212,
    "ma_bt": "0212",
    "name": "Mẫu tử",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm – Xanh đồng",
    "size": "30*50 cm",
    "period": "2011",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0212.jpeg"
  },
  {
    "id": 213,
    "ma_bt": "0213",
    "name": "Thác nước",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Vàng",
    "size": "50*65 cm",
    "period": "2007",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0213.jpeg"
  },
  {
    "id": 214,
    "ma_bt": "0214",
    "name": "Xoay gốm",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm",
    "size": "35*70 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0214.jpeg"
  },
  {
    "id": 215,
    "ma_bt": "0215",
    "name": "Chọi trâu",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu vàng",
    "size": "60*70 cm",
    "period": "2008",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0215.jpeg"
  },
  {
    "id": 216,
    "ma_bt": "0216",
    "name": "Suy tư",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm – Xanh cô ban",
    "size": "50*70 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0216.jpeg"
  },
  {
    "id": 217,
    "ma_bt": "0217",
    "name": "Đài kỷ niệm Biên hòa",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Nâu",
    "size": "40*80 cm",
    "period": "1997",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0217.jpeg"
  },
  {
    "id": 218,
    "ma_bt": "0218",
    "name": "Bình Hoa",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu đất",
    "size": "30*65 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0218.jpeg"
  },
  {
    "id": 219,
    "ma_bt": "0219",
    "name": "Bình 1 dây lá",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "40*85 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0219.jpeg"
  },
  {
    "id": 220,
    "ma_bt": "0220",
    "name": "Bình Bầu rượu",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu",
    "size": "35*55 cm",
    "period": "2000s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0220.jpeg"
  },
  {
    "id": 221,
    "ma_bt": "0221",
    "name": "Tốt nghiệp",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm  - Xanh đồng",
    "size": "20*40 cm",
    "period": "2003",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0221.jpeg"
  },
  {
    "id": 222,
    "ma_bt": "0222",
    "name": "Hũ Da lươn",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Màu da lươn",
    "size": "22*30cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0222.jpeg"
  },
  {
    "id": 223,
    "ma_bt": "0223",
    "name": "Cây đèn dầu",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Xanh nâu",
    "size": "15*30 cm",
    "period": "2003",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0223.jpeg"
  },
  {
    "id": 224,
    "ma_bt": "0224",
    "name": "Bình Hai rồng",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu",
    "size": "30*50 cm",
    "period": "1990s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0224.jpeg"
  },
  {
    "id": 225,
    "ma_bt": "0225",
    "name": "Ếch xanh đồng",
    "category": "Điêu khắc",
    "filterKey": "Điêu khắc",
    "material": "Thạch cao",
    "size": "30*50 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0225.jpeg"
  },
  {
    "id": 226,
    "ma_bt": "0226",
    "name": "Tượng La hán",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Đất nung phủ sơn màu nâu",
    "size": "30*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0226.jpeg"
  },
  {
    "id": 227,
    "ma_bt": "0227",
    "name": "Chậu Bon sai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu măng",
    "size": "40*15 cm",
    "period": "2008",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0227.jpeg"
  },
  {
    "id": 228,
    "ma_bt": "0228",
    "name": "Thổi tù và",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu đen",
    "size": "22*60 cm",
    "period": "2000",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0228.jpeg"
  },
  {
    "id": 229,
    "ma_bt": "0229",
    "name": "Bình hai quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "25*35 cm",
    "period": "1960s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0229.jpeg"
  },
  {
    "id": 230,
    "ma_bt": "0230",
    "name": "Bình Xoắn trôn ốc",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Vàng",
    "size": "22*30 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0230.jpeg"
  },
  {
    "id": 231,
    "ma_bt": "0231",
    "name": "Chân đèn",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm - Xanh đồng",
    "size": "40*40 cm",
    "period": "1980s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0231.jpeg"
  },
  {
    "id": 232,
    "ma_bt": "0232",
    "name": "Mẫu Tử",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu vàng",
    "size": "30*40 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0232.jpeg"
  },
  {
    "id": 233,
    "ma_bt": "0233",
    "name": "Bình Chim hạc",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng nâu",
    "size": "30*60 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0233.jpeg"
  },
  {
    "id": 234,
    "ma_bt": "0234",
    "name": "Bình Bưởi",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Da lươn",
    "size": "40*70 cm",
    "period": "1997",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0234.jpeg"
  },
  {
    "id": 235,
    "ma_bt": "0235",
    "name": "Gió xuân",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Vàng",
    "size": "15*25 cm",
    "period": "2007",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0235.jpeg"
  },
  {
    "id": 236,
    "ma_bt": "0236",
    "name": "Ba nét mặt",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Vàng",
    "size": "15*25 cm",
    "period": "2000",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0236.jpeg"
  },
  {
    "id": 237,
    "ma_bt": "0237",
    "name": "Bình hoa lộng đất nung",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Trắng ta",
    "size": "20*28 cm",
    "period": "1999",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0237.jpeg"
  },
  {
    "id": 238,
    "ma_bt": "0238",
    "name": "Chân đèn tam rồng",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm – Xanh đồng",
    "size": "15*40 cm",
    "period": "1998",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0238.jpeg"
  },
  {
    "id": 239,
    "ma_bt": "0239",
    "name": "Bát Trang trí",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh",
    "size": "10*17 cm",
    "period": "2015",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0239.jpeg"
  },
  {
    "id": 240,
    "ma_bt": "00240",
    "name": "Chân Đèn tam rồng",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm – Xanh đồng",
    "size": "15*40 cm",
    "period": "1998",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/00240.jpeg"
  },
  {
    "id": 241,
    "ma_bt": "0241",
    "name": "Chậu nhỏ dây lá",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "10*20 cm",
    "period": "1970s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0241.jpeg"
  },
  {
    "id": 242,
    "ma_bt": "0242",
    "name": "Bình Trà nai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm – Xanh đồng",
    "size": "20*22 cm",
    "period": "2002",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0242.jpeg"
  },
  {
    "id": 243,
    "ma_bt": "0243",
    "name": "Bình Nét tuổi thơ",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu",
    "size": "25*20 cm",
    "period": "2003",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0243.jpeg"
  },
  {
    "id": 244,
    "ma_bt": "0244",
    "name": "Mùa xuân",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Xanh đồng",
    "size": "18*24 cm",
    "period": "2003",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0244.jpeg"
  },
  {
    "id": 245,
    "ma_bt": "0245",
    "name": "Hũ xanh đồng 4 quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh đồng",
    "size": "28*35 cm",
    "period": "2003",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0245.jpeg"
  },
  {
    "id": 246,
    "ma_bt": "0246",
    "name": "Chị em",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Xanh dương",
    "size": "40*40 cm",
    "period": "1998",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0246.jpeg"
  },
  {
    "id": 247,
    "ma_bt": "0247",
    "name": "Cặp đôi",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu sậm",
    "size": "25*35 cm",
    "period": "2003",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0247.jpeg"
  },
  {
    "id": 248,
    "ma_bt": "0248",
    "name": "Môi trường biển",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Vàng",
    "size": "25*60 cm",
    "period": "2005",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0248.jpeg"
  },
  {
    "id": 249,
    "ma_bt": "0249",
    "name": "Ghép",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm – Nâu lươn",
    "size": "30*30 cm",
    "period": "2005",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0249.jpeg"
  },
  {
    "id": 250,
    "ma_bt": "0250",
    "name": "Chân đèn nhỏ",
    "category": "Đèn & Trang trí",
    "filterKey": "Đèn",
    "material": "Gốm",
    "size": "10*22 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0250.jpeg"
  },
  {
    "id": 251,
    "ma_bt": "0251",
    "name": "Bình hoa nhỏ",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Đen",
    "size": "10*35 cm",
    "period": "2001",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0251.jpeg"
  },
  {
    "id": 252,
    "ma_bt": "0252",
    "name": "Bình Tứ linh",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu xanh đồng",
    "size": "50*100 cm",
    "period": "2011",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0252.jpeg"
  },
  {
    "id": 253,
    "ma_bt": "0253",
    "name": "Bình tứ linh",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu xanh đồng",
    "size": "50*100 cm",
    "period": "2011",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0253.jpeg"
  },
  {
    "id": 254,
    "ma_bt": "0254",
    "name": "Nam tào",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - xanh đồng",
    "size": "40*90 cm",
    "period": "2011",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0254.jpeg"
  },
  {
    "id": 255,
    "ma_bt": "0255",
    "name": "Nam tào",
    "category": "Tượng",
    "filterKey": "Tượng",
    "material": "Gốm - Xanh đồng",
    "size": "40*90 cm",
    "period": "2011",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0255.jpeg"
  },
  {
    "id": 256,
    "ma_bt": "0256",
    "name": "Đồng nai",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm – Xanh đồng",
    "size": "30*60 cm",
    "period": "1998",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0256.jpeg"
  },
  {
    "id": 257,
    "ma_bt": "0257",
    "name": "Bình trà Thổ cẩm",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu đen",
    "size": "30*30 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0257.jpeg"
  },
  {
    "id": 258,
    "ma_bt": "0258",
    "name": "Bình Monkey",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Đất nung",
    "size": "30*40 cm",
    "period": "2003",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0258.jpeg"
  },
  {
    "id": 259,
    "ma_bt": "0259",
    "name": "Tiếng trống Paranưng",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm - Nâu đỏ",
    "size": "30*70 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0259.jpeg"
  },
  {
    "id": 260,
    "ma_bt": "0260",
    "name": "Âm vang Tây nguyên",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Nâu",
    "size": "40*50 cm",
    "period": "2004",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0260.jpeg"
  },
  {
    "id": 261,
    "ma_bt": "0261",
    "name": "Sức sống",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm  - Xanh đỏ",
    "size": "30*50 cm",
    "period": "1993",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0261.jpeg"
  },
  {
    "id": 262,
    "ma_bt": "0262",
    "name": "Rồng lá 3 quai",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm - Xanh cô ban",
    "size": "30*50 cm",
    "period": "1993",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0262.jpeg"
  },
  {
    "id": 263,
    "ma_bt": "0263",
    "name": "Địu con",
    "category": "Gốm sáng tác",
    "filterKey": "Sáng tác",
    "material": "Gốm – Nâu vàng",
    "size": "25*60 cm",
    "period": "2000s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0263.jpeg"
  },
  {
    "id": 264,
    "ma_bt": "0264",
    "name": "Cầu Mỹ thuận",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Nâu đỏ",
    "size": "30*45 cm",
    "period": "1998",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0264.jpeg"
  },
  {
    "id": 265,
    "ma_bt": "0265",
    "name": "Bình Mùa thu",
    "category": "Bình & Lọ",
    "filterKey": "Bình",
    "material": "Gốm",
    "size": "25*50 cm",
    "period": "1996",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0265.jpeg"
  },
  {
    "id": 266,
    "ma_bt": "0266",
    "name": "Cao su",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Xanh đồng",
    "size": "30*70 cm",
    "period": "2000s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0266.jpeg"
  },
  {
    "id": 267,
    "ma_bt": "0267",
    "name": "Cao su",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Xanh đồng",
    "size": "35*75 cm",
    "period": "2000s",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0267.jpeg"
  },
  {
    "id": 268,
    "ma_bt": "0268",
    "name": "Nghìn năm Thăng long",
    "category": "Phù điêu & Tranh",
    "filterKey": "Phù điêu",
    "material": "Gốm - Nâu đỏ",
    "size": "60*100 cm",
    "period": "2010",
    "origin": "TRƯỜNG CAO ĐẲNG MỸ THUẬT TRANG TRÍ ĐỒNG NAI",
    "img": "images/collection/0268.jpeg"
  }
];
